hznuoj2.2
hznuoj-dev/hznuoj pull request #12
Opened 2024-02-04 13:54 UTC by daizeyao

新增功能：
学生端：
1、题目页面tag
2、题目页面gptcode
3、个人页面每日学习情况
4、个人页面学习里程碑
管理员端：
1、管理所有题目tag种类
2、增删改查某道题tag
3、增删改查某道题gptcode
4、修改每日学习情况起始终止时间

2024-02-06 00:20 UTC, Dup4 requested changes

2024-02-06 00:20 UTC, Dup4 commented on scripts/db.sql
> --- MySQL dump 10.13  Distrib 5.7.25, for Linux (x86_64)
除了这份完整的 SQL，您再提交一份增量更新的 SQL 吧
上线的时候并不能执行这份完整的 SQL，对吧，毕竟里面到处都是 DROP TABLE IF EXISTS `xxx`;，一执行，原来的表都会被 DROP 掉

2024-02-06 02:13 UTC, daizeyao commented on scripts/db.sql
> --- MySQL dump 10.13  Distrib 5.7.25, for Linux (x86_64)
更新了scripts/dbforadd2.2.sql，除了privilege_distribution都为新增的表，privilege_distribution新增了三个字段

2024-02-06 02:26 UTC, Dup4 requested changes

2024-02-06 02:26 UTC, Dup4 commented on scripts/dbforadd2.2.sql
> +DROP TABLE IF EXISTS `privilege_distribution`;
这张表应该是本来就存在的？
那应该不能用「重新建表」的方式来「上线」？
应该用 UPDATE 表结构的方式？

2024-02-06 02:41 UTC, daizeyao commented on scripts/dbforadd2.2.sql
> +DROP TABLE IF EXISTS `privilege_distribution`;
抱歉，我没有注意到这个问题，现在已经更新了

2024-02-06 23:58 UTC, Dup4 commented on scripts/dbforadd2.2.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;
CHARSET 不要用 latin1 吧，用 utf8mb4
AUTO_INCREMENT=28 都改成 AUTO_INCREMENT=1 吧
你这应该是直接 dump 下来的表结构吧

2024-02-06 23:59 UTC, Dup4 commented on scripts/db.sql
> +INSERT INTO `contest` VALUES (1,'123','2024-01-29 21:00:00','2024-01-30 01:00:00','N','',0,0,'','N','N','N',NULL,1,0,0,0,0),(2,'111111','2024-01-30 19:00:00','2024-01-30 23:00:00','N','',0,0,'','N','
为什么要往 contest 中 INSERT 一条这样的数据？

2024-02-07 00:57 UTC, daizeyao commented on scripts/dbforadd2.2.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;
有需要用到utf8的部分进行了修改。
一些冗余数据包括AUTO_INCREMENT也进行了修改

2024-02-07 00:57 UTC, daizeyao commented on scripts/db.sql
> +INSERT INTO `contest` VALUES (1,'123','2024-01-29 21:00:00','2024-01-30 01:00:00','N','',0,0,'','N','N','N',NULL,1,0,0,0,0),(2,'111111','2024-01-30 19:00:00','2024-01-30 23:00:00','N','',0,0,'','N','
已修改

2024-02-09 23:39 UTC, Dup4 commented on scripts/dbforadd2.2.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;
不要用 utf8，要用 utf8mb4
至于为什么可以看：https://cloud.tencent.com/developer/article/1930660

另外，也不要用 latin1，我们不需要这点存储空间的优化
我的建议是直接无脑用 utf8mb4 就完了

2024-02-09 23:44 UTC, Dup4 commented on web/OJ/image/temp.jpg
话说这张图是有什么用？会出现在哪里？

2024-02-09 23:47 UTC, Dup4 commented on scripts/dbforadd2.2.sql
> +INSERT INTO `dailydetails` VALUES ('2023-09-01','2024-02-01');
这些数据是 「迁移表结构」过程中必须要插入的数据吗？
还是说只是因为你用于开发的 DB 里面存在，然后你无脑 dump 下来，所以出现在这里

2024-02-09 23:49 UTC, daizeyao commented on web/OJ/image/temp.jpg
当时做测试的时候添加的，稍等我会删掉

2024-02-09 23:50 UTC, daizeyao commented on scripts/dbforadd2.2.sql
> +INSERT INTO `dailydetails` VALUES ('2023-09-01','2024-02-01');
这个是必须要存在的，图表需要起止时间，后续可以修改，就默认搞了个时间

2024-02-10 00:14 UTC, daizeyao commented on scripts/dbforadd2.2.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;
进行了修改，对于原来使用utf8的保留了utf8，新增都使用了utf8mb4

2024-02-26 04:50 UTC, merged